### ISSUE TITLE
NITContent

### ISSUE THREAD

**Issue by nferruzzi** [nearit/Near-iOS-SDK#2]
Ciao,
stavo provando a mandarmi una notifica con un link ad un pdf, ma non lo vedo nel dizionario che ricevo . Allego dump

```
{
    "app_id" = "77819f5d-bcb2-43f5-8ff5-7a6f593f5c92";
    "audio_id" = "";
    content = "<h1 style=\"text-align: center;\">Near\U00a0</h1><h1><br/></h1>";
    "created_at" = "2017-08-10T16:03:42.109987Z";
    "image_ids" =     (
        "81efcb26-c837-4adb-8c89-c9d88d36e8cb"
    );
    "owner_id" = "00308695-15c8-4963-b2bd-fc477d4595a3";
    "updated_at" = "2017-08-10T16:03:42.109987Z";
    "upload_id" = "3ba37172-6a42-474d-9e5a-b1786d213742";
    "video_link" = "<null>";
}
```

per il dump uso

`debugPrint(c.resourceObject?.toDictionary())`

dove `c` e' di tipo NITContent

grazie in anticipo

**Comment by nferruzzi** [comment]
Ok penso di aver capito che e' "upload" quello che mi serve, per i file

**Comment by TheFlynn** [comment]
Esatto, è l'oggetto "upload" (di tipo NITUpload) che ti serve, poi sostanzialmente da lì puoi avere l'url della risorsa che ti serve, che sia pdf o altro.

**Comment by nferruzzi** [comment]
grazie per la conferma
