### ISSUE TITLE
titolo notifica in notifiche con contenuto su iOS

### ISSUE THREAD

**Issue by nferruzzi** [nearit/Near-iOS-SDK#3]
Ciao,
da pannello di controllo mi mando una notifica di test con contenuto e ne imposto il titolo ed il testo. Quando la ricevo tramite l'sdk pero' il titolo della notifica non e' disponibile ne' come titolo della ricetta ne' come titolo nel contenuto:

```
Content received: <NITContent: 0x174262cc0>
{
  "image_link" : null,
  "data" : "2017-08-23T07:45:41.177+0000",
  "text" : "<p>testo notifica<\/p>",
  "message_type" : 2,
  "pdf_link" : null,
  "title" : null,
  "NewsID" : "4f5d8926-caa8-4fbc-8324-7139fb7d7305"
}
(lldb) po recipe.notificationTitle()
nil
```

**Comment by TheFlynn** [comment]
Ciao,
il titolo è stato rimosso dal cms di Near, è rimasta la variabile "title" ma non sarà mai valorizzata, nemmeno nella ricetta.
